### ISSUE TITLE
Checking in

### ISSUE THREAD

**Issue by karthik** [dmpe/rbitly#1]
Thanks for adding me to the repo. I assume you saw some earlier work I started but never got around to completing. Happy to help if you need a collaborator. Cheers.

**Comment by dmpe** [comment]
Yop. Thank you @karthik very much for the offer!
I added you (together with @hadley too) in part because of the https://github.com/ropensci organisation. So, once I will finish the work on it (covering useful API, tests, docu), I could transfer the ownership to rOpenSci (in that the package will have a better future in addition).

**Comment by karthik** [comment]
@dmpe Sounds great! We now have a streamlined way to onboard packages so this should go smoothly. I'll watch the repo and contribute accordingly but please ping on issues as/when you need to delegate on tasks.

**Comment by dmpe** [comment]
@karthik Ok, will definitely do. Currently, I kind of need more users to test it as I have already covered `link metrics` and some `user's metrics`. Especially, with `custom domains` (e.g. nyti.ms, cnb.cx) and bigger accounts. Because my tests run on 1 shorted bit.ly (!) URL and this is to small to make sure that it works properly.

This is currently my roadmap:

**Minor**
- [ ] Make sure one can clone, load & build the `rbitly` -> continuing task
- [ ] Keep writing "good" documentation & tests
- [x] Add Travis & Coverage


**Major**
- [ ] Cover most of the free (i.e. non-pro) API -> will take some time (June, July)
- [ ] Catch most of bugs through testing with "big Bit.ly accounts"
